@startuml DockContainers
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml


top to bottom direction
skinparam linetype ortho
skinparam nodesep 120
skinparam ranksep 140
skinparam padding 8

Person(LOA, "Logistics Operator", "System user managing logistics operations")

System_Boundary(sms, "Shipping Management System") {
    Container(Staffapi, "Staff API", ".NET 8 (ASP.NET Core Web API)", "Provides endpoints to manage staff (create, update, list)")
    Container(StaffContainer, "Staff Container", "ASP.NET Code MVC Controller", "Handles HTTP requests related to staff management")
    Container(StaffService, "Staff Service", ".NET 8 (ASP.NET Core)", "Business logic for staff management")
    Container(Staff, "Staff", "Domain Model", "Represents staff")
    Container(Resource, "Resource", "Domain Model", "Represents types of resources")
    Container(ResourceStatus, "Resource Status", "Domain Model", "Represents status of resources")
    Container(OperationalWindow, "Operational Window", "Domain Model", "Represents operational time windows")
    Container(Qualification, "Qualification", "Domain Model", "Represents Resources qualifications")
    Container(StaffRepository, "Staff Repository", ".NET 8 (ASP.NET Core)", "Data access for staff")
    Container(StaffDb, "Staff DbContext", "NET 8 (Entity Framework Core)", "EF Core DbContext for staff")
    Container(ShippingDb, "Shipping Management Database", "SQL Server", "Stores all data related to shipping management")
}

Rel(LOA, Staffapi, "Sends HTTP requests via ...", "HTTPS/JSON")
Rel(Staffapi, StaffContainer, "Routes request to", "Method Calls")
Rel(StaffContainer, StaffService, "Calls methods in", "Method Calls")
Rel(Resource, Staff, "Extends", "Domain Logic")
Rel(StaffService, Resource, "Uses", "Domain Logic")
Rel(Resource, ResourceStatus, "Uses", "Domain Logic")
Rel(Resource, OperationalWindow, "Uses", "Domain Logic")
Rel(Resource, Qualification, "Uses", "Domain Logic")
Rel(StaffService, StaffRepository, "Uses", "Method Calls")
Rel(StaffRepository, StaffDb, "Uses", "Method Calls")
Rel(StaffDb, ShippingDb, "Reads from and writes to", "EF Core/SQL")

@enduml