@startuml 2.2.11
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

actor "Logistics Operator" as LogisticsOperator
participant "System" as system

title System Sequence Diagram - US2.2.11

== Deactivate a staff ==
activate LogisticsOperator

LogisticsOperator -> system : Asks to update staff 
activate system

system --> LogisticsOperator : Asks for staff id
deactivate system

LogisticsOperator -> system : Types staff id
activate system

system --> LogisticsOperator : Deactivates the staff and displays operation success


@enduml
