@startuml 2.2.11
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

actor "Logistics Operator" as LogisticsOperator
participant "System" as system

title System Sequence Diagram - US2.2.11

== Register a staff ==
activate LogisticsOperator

LogisticsOperator -> system : Asks to register staff 
activate system

system --> LogisticsOperator : Request staff information("ID, Short Name,\n Email, Phone, Qualifications Code, Operations Window, Status")
deactivate system
LogisticsOperator -> system : Types request data

activate system
system --> LogisticsOperator : Displays operation success
deactivate system




@enduml
