@startuml 2.2.11
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

actor "Logistics Operator" as LogisticsOperator
participant "System" as system

title System Sequence Diagram - US2.2.11

== Deactivate a staff menber ==
activate LogisticsOperator

LogisticsOperator -> system : Asks to update staff menbers
activate system

system --> LogisticsOperator : Displays staff menbers
deactivate system

LogisticsOperator -> system : Selects a staff menber
activate system

system --> LogisticsOperator : Deactivates the staff menber\nand displays operation success


@enduml
