@startuml 2.2.8
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

actor "Shipping Agent Representative" as shippingAgentRepresentative
participant "System" as system

title System Sequence Diagram - US2.2.8

== Create/Submit Vessel Visit Notification ==
activate shippingAgentRepresentative

shippingAgentRepresentative -> system : Asks to create/submit a vessel visit notification
activate system

system -> shippingAgentRepresentative : Request data(vessel, expected arrival, expected departure,\n cargo manifest, cargo type, crew)
deactivate system
shippingAgentRepresentative -> system : Provides requested data

activate system
system -> shippingAgentRepresentative : Displays operation success
deactivate system

@enduml
