import { Service, Inject } from 'typedi';
import IComplementaryTaskService from './IServices/IComplementaryTaskService';
import IComplementaryTaskRepo from './IRepos/IComplementaryTaskRepo';
import IVesselVisitExecutionRepo from './IRepos/IVesselVisitExecutionRepo';
import { ComplementaryTask } from '../domain/ComplementaryTask';
import { ComplementaryTaskDTO, CreateComplementaryTaskDTO, UpdateComplementaryTaskDTO } from '../dto/ComplementaryTaskDTO';
import { ComplementaryTaskMap } from '../mappers/ComplementaryTaskMap';
import { Result } from '../core/logic/Result';
import { ComplementaryTaskStatus } from '../domain/ComplementaryTaskEnums';

@Service()
export default class ComplementaryTaskService implements IComplementaryTaskService {

    constructor(
        @Inject("complementaryTaskRepo") private complementaryTaskRepo: IComplementaryTaskRepo,
        @Inject("vesselVisitExecutionRepo") private vesselVisitExecutionRepo: IVesselVisitExecutionRepo,
        @Inject("logger") private logger: any
    ) {}

    public async createComplementaryTask(dto: CreateComplementaryTaskDTO): Promise<Result<ComplementaryTaskDTO>> {
        try {
            // Validate that the vessel visit execution exists
            const vve = await this.vesselVisitExecutionRepo.findByCode(dto.vesselVisitExecutionCode);
            if (!vve) {
                return Result.fail(`Vessel visit execution with code ${dto.vesselVisitExecutionCode} not found.`);
            }

            // Create the complementary task
            const startTime = typeof dto.startTime === 'string' ? new Date(dto.startTime) : dto.startTime;
            const endTime = dto.endTime ? (typeof dto.endTime === 'string' ? new Date(dto.endTime) : dto.endTime) : undefined;

            const task = new ComplementaryTask(
                "", // ID will be generated by MongoDB
                dto.category,
                dto.responsibleTeam,
                startTime,
                ComplementaryTaskStatus.Ongoing, // Default status
                dto.vesselVisitExecutionCode,
                dto.suspendsOperations,
                endTime,
                dto.description
            );

            const savedTask = await this.complementaryTaskRepo.save(task);
            const taskDTO = ComplementaryTaskMap.toDTO(savedTask);

            this.logger.info(`Created complementary task with ID: ${savedTask.id}`);
            return Result.ok(taskDTO);

        } catch (error) {
            this.logger.error(error);
            return Result.fail(`Error creating complementary task: ${error.message}`);
        }
    }

    public async updateComplementaryTask(id: string, dto: UpdateComplementaryTaskDTO): Promise<Result<ComplementaryTaskDTO>> {
        try {
            const existingTask = await this.complementaryTaskRepo.findById(id);
            if (!existingTask) {
                return Result.fail(`Complementary task with ID ${id} not found.`);
            }

            // Update fields if provided
            if (dto.category !== undefined) {
                // Re-create the task with updated category - validation happens in constructor
                const updatedTask = new ComplementaryTask(
                    existingTask.id,
                    dto.category,
                    dto.responsibleTeam ?? existingTask.responsibleTeam,
                    existingTask.startTime,
                    dto.status ?? existingTask.status,
                    existingTask.vesselVisitExecutionCode,
                    dto.suspendsOperations ?? existingTask.suspendsOperations,
                    dto.endTime ? (typeof dto.endTime === 'string' ? new Date(dto.endTime) : dto.endTime) : existingTask.endTime,
                    dto.description ?? existingTask.description
                );

                const updated = await this.complementaryTaskRepo.update(updatedTask);
                if (!updated) {
                    return Result.fail(`Failed to update complementary task with ID ${id}.`);
                }

                const taskDTO = ComplementaryTaskMap.toDTO(updated);
                this.logger.info(`Updated complementary task with ID: ${id}`);
                return Result.ok(taskDTO);

            } else {
                // Update individual fields
                if (dto.responsibleTeam !== undefined) {
                    existingTask.responsibleTeam = dto.responsibleTeam;
                }

                if (dto.endTime !== undefined) {
                    const endTime = typeof dto.endTime === 'string' ? new Date(dto.endTime) : dto.endTime;
                    existingTask.updateEndTime(endTime);
                }

                if (dto.status !== undefined) {
                    existingTask.updateStatus(dto.status, existingTask.endTime);
                }

                if (dto.suspendsOperations !== undefined) {
                    existingTask.suspendsOperations = dto.suspendsOperations;
                }

                if (dto.description !== undefined) {
                    existingTask.updateDescription(dto.description);
                }

                const updated = await this.complementaryTaskRepo.update(existingTask);
                if (!updated) {
                    return Result.fail(`Failed to update complementary task with ID ${id}.`);
                }

                const taskDTO = ComplementaryTaskMap.toDTO(updated);
                this.logger.info(`Updated complementary task with ID: ${id}`);
                return Result.ok(taskDTO);
            }

        } catch (error) {
            this.logger.error(error);
            return Result.fail(`Error updating complementary task: ${error.message}`);
        }
    }

    public async getComplementaryTaskById(id: string): Promise<Result<ComplementaryTaskDTO>> {
        try {
            const task = await this.complementaryTaskRepo.findById(id);
            if (!task) {
                return Result.fail(`Complementary task with ID ${id} not found.`);
            }

            const taskDTO = ComplementaryTaskMap.toDTO(task);
            return Result.ok(taskDTO);

        } catch (error) {
            this.logger.error(error);
            return Result.fail(`Error getting complementary task: ${error.message}`);
        }
    }

    public async getAllComplementaryTasks(): Promise<Result<ComplementaryTaskDTO[]>> {
        try {
            const tasks = await this.complementaryTaskRepo.findAll();
            const dtoList = tasks.map(task => ComplementaryTaskMap.toDTO(task));
            return Result.ok(dtoList);

        } catch (error) {
            this.logger.error(error);
            return Result.fail("Error getting all complementary tasks.");
        }
    }

    public async getComplementaryTasksByVesselVisit(vveCode: string): Promise<Result<ComplementaryTaskDTO[]>> {
        try {
            const tasks = await this.complementaryTaskRepo.findByVesselVisitExecutionCode(vveCode);
            const dtoList = tasks.map(task => ComplementaryTaskMap.toDTO(task));
            return Result.ok(dtoList);

        } catch (error) {
            this.logger.error(error);
            return Result.fail(`Error getting complementary tasks for vessel visit ${vveCode}.`);
        }
    }

    public async getComplementaryTasksByStatus(status: ComplementaryTaskStatus): Promise<Result<ComplementaryTaskDTO[]>> {
        try {
            const tasks = await this.complementaryTaskRepo.findByStatus(status);
            const dtoList = tasks.map(task => ComplementaryTaskMap.toDTO(task));
            return Result.ok(dtoList);

        } catch (error) {
            this.logger.error(error);
            return Result.fail(`Error getting complementary tasks by status.`);
        }
    }

    public async getComplementaryTasksByDateRange(startDate: Date, endDate: Date): Promise<Result<ComplementaryTaskDTO[]>> {
        try {
            const tasks = await this.complementaryTaskRepo.findByDateRange(startDate, endDate);
            const dtoList = tasks.map(task => ComplementaryTaskMap.toDTO(task));
            return Result.ok(dtoList);

        } catch (error) {
            this.logger.error(error);
            return Result.fail(`Error getting complementary tasks by date range.`);
        }
    }

    public async getOngoingTasksThatSuspendOperations(): Promise<Result<ComplementaryTaskDTO[]>> {
        try {
            const tasks = await this.complementaryTaskRepo.findOngoingThatSuspendOperations();
            const dtoList = tasks.map(task => ComplementaryTaskMap.toDTO(task));
            return Result.ok(dtoList);

        } catch (error) {
            this.logger.error(error);
            return Result.fail("Error getting ongoing tasks that suspend operations.");
        }
    }

    public async deleteComplementaryTask(id: string): Promise<Result<void>> {
        try {
            const task = await this.complementaryTaskRepo.findById(id);
            if (!task) {
                return Result.fail(`Complementary task with ID ${id} not found.`);
            }

            const deleted = await this.complementaryTaskRepo.delete(id);
            if (!deleted) {
                return Result.fail(`Failed to delete complementary task with ID ${id}.`);
            }

            this.logger.info(`Deleted complementary task with ID: ${id}`);
            return Result.ok<void>();

        } catch (error) {
            this.logger.error(error);
            return Result.fail(`Error deleting complementary task: ${error.message}`);
        }
    }
}
